apiVersion: batch/v1
kind: Job
metadata:
  name: hellojob
spec:
  completions: 3
  parallelism: 2
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers: 
          - name: mycont
            image: luksa/batch-job
      